[project]
name = "datalake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dask>=2026.6.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.0",
    "nco>=1.1.2",
    "netcdf4>=1.7.4",
    "notebook>=7.6.0",
    "pandas>=3.0.3",
    "watchdog>=6.0.0",
    "xarray>=2026.4.0",
]
